#############################################################################
# Makefile for building: MAIN_MOBILE
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  MAIN_MOBILE.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile MAIN_MOBILE.pro -spec linux-g++ CONFIG+=debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = ccache gcc
CXX           = ccache g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MAIN_MOBILE1.0.0
DISTDIR = /home/rainbow/UI_MOBILE_TEMP/.tmp/MAIN_MOBILE1.0.0
LINK          = g++
LFLAGS        = -fuse-ld=gold
LIBS          = $(SUBLIBS) -lpython3.10 -L/usr/lib/x86_64-linux-gnu/ -L/usr/lib/aarch64-linux-gnu/ -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_objdetect -lopencv_photo -lopencv_video -lopencv_videoio -lboost_system -lopencv_ximgproc -L/usr/local/lib/ -lz -lusb-1.0 /usr/lib/x86_64-linux-gnu/libQt5QuickControls2.so /usr/lib/x86_64-linux-gnu/libQt5Quick.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5QmlModels.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5WebSockets.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = CallbellHandler.cpp \
		CameraView.cpp \
		ExtProcess.cpp \
		IPCHandler.cpp \
		MapHandler.cpp \
		MapViewer.cpp \
		ServerHandler.cpp \
		ZIPHandler.cpp \
		automata.cpp \
		cv_to_qt.cpp \
		Logger.cpp \
		Supervisor.cpp \
		main.cpp \
		quazip/JlCompress.cpp \
		quazip/qioapi.cpp \
		quazip/quaadler32.cpp \
		quazip/quachecksum32.cpp \
		quazip/quacrc32.cpp \
		quazip/quagzipfile.cpp \
		quazip/quaziodevice.cpp \
		quazip/quazip.cpp \
		quazip/quazipdir.cpp \
		quazip/quazipfile.cpp \
		quazip/quazipfileinfo.cpp \
		quazip/quazipnewinfo.cpp \
		quazip/unzip.c \
		quazip/zip.c \
		websocket/QtHttpServer.cpp \
		websocket/QtHttpReply.cpp \
		websocket/QtHttpRequest.cpp \
		websocket/QtHttpHeader.cpp \
		websocket/QtHttpClientWrapper.cpp Popup_notice_qml.cpp \
		Item_radioButton_qml.cpp \
		Popup_patrol_qml.cpp \
		Popup_password_qml.cpp \
		Page_moving_qml.cpp \
		Page_charge_qml.cpp \
		Tool_Keyboard_qml.cpp \
		Item_button_qml.cpp \
		Item_menubar_qml.cpp \
		Popup_help_qml.cpp \
		Page_pickup_qml.cpp \
		Page_MoveFail_qml.cpp \
		Item_buttons_qml.cpp \
		Item_statusbar_qml.cpp \
		Page_setting_qml.cpp \
		MAP_FULL2_qml.cpp \
		main_qml.cpp \
		Page_init_qml.cpp \
		Item_localization_qml.cpp \
		Item_progressCircle_qml.cpp \
		Page_kitchen_qml.cpp \
		Popup_patrol_page_qml.cpp \
		Page_mapping_qml.cpp \
		Page_menus_qml.cpp \
		Tool_KeyPad_qml.cpp \
		Page_pickup_calling_qml.cpp \
		Popup_map_list_qml.cpp \
		Item_ProgressBar_qml.cpp \
		Popup_test_tts_qml.cpp \
		Page_log_qml.cpp \
		Page_map_qml.cpp \
		Item_CircleP_qml.cpp \
		Item_buttonRectIcon_qml.cpp \
		Page_annotation_qml.cpp \
		qmlcache_loader.cpp \
		qrc_qml_qmlcache.cpp \
		moc_CallbellHandler.cpp \
		moc_CameraView.cpp \
		moc_ExtProcess.cpp \
		moc_IPCHandler.cpp \
		moc_MapHandler.cpp \
		moc_MapViewer.cpp \
		moc_ServerHandler.cpp \
		moc_Keyemitter.cpp \
		moc_Logger.cpp \
		moc_MapHeader.cpp \
		moc_ZIPHandler.cpp \
		moc_Supervisor.cpp \
		moc_quagzipfile.cpp \
		moc_quaziodevice.cpp \
		moc_quazipfile.cpp \
		moc_QtHttpServer.cpp \
		moc_QtHttpReply.cpp \
		moc_QtHttpRequest.cpp \
		moc_QtHttpClientWrapper.cpp
OBJECTS       = CallbellHandler.o \
		CameraView.o \
		ExtProcess.o \
		IPCHandler.o \
		MapHandler.o \
		MapViewer.o \
		ServerHandler.o \
		ZIPHandler.o \
		automata.o \
		cv_to_qt.o \
		Logger.o \
		Supervisor.o \
		main.o \
		JlCompress.o \
		qioapi.o \
		quaadler32.o \
		quachecksum32.o \
		quacrc32.o \
		quagzipfile.o \
		quaziodevice.o \
		quazip.o \
		quazipdir.o \
		quazipfile.o \
		quazipfileinfo.o \
		quazipnewinfo.o \
		unzip.o \
		zip.o \
		QtHttpServer.o \
		QtHttpReply.o \
		QtHttpRequest.o \
		QtHttpHeader.o \
		QtHttpClientWrapper.o \
		Popup_notice_qml.o \
		Item_radioButton_qml.o \
		Popup_patrol_qml.o \
		Popup_password_qml.o \
		Page_moving_qml.o \
		Page_charge_qml.o \
		Tool_Keyboard_qml.o \
		Item_button_qml.o \
		Item_menubar_qml.o \
		Popup_help_qml.o \
		Page_pickup_qml.o \
		Page_MoveFail_qml.o \
		Item_buttons_qml.o \
		Item_statusbar_qml.o \
		Page_setting_qml.o \
		MAP_FULL2_qml.o \
		main_qml.o \
		Page_init_qml.o \
		Item_localization_qml.o \
		Item_progressCircle_qml.o \
		Page_kitchen_qml.o \
		Popup_patrol_page_qml.o \
		Page_mapping_qml.o \
		Page_menus_qml.o \
		Tool_KeyPad_qml.o \
		Page_pickup_calling_qml.o \
		Popup_map_list_qml.o \
		Item_ProgressBar_qml.o \
		Popup_test_tts_qml.o \
		Page_log_qml.o \
		Page_map_qml.o \
		Item_CircleP_qml.o \
		Item_buttonRectIcon_qml.o \
		Page_annotation_qml.o \
		qmlcache_loader.o \
		qrc_qml_qmlcache.o \
		moc_CallbellHandler.o \
		moc_CameraView.o \
		moc_ExtProcess.o \
		moc_IPCHandler.o \
		moc_MapHandler.o \
		moc_MapViewer.o \
		moc_ServerHandler.o \
		moc_Keyemitter.o \
		moc_Logger.o \
		moc_MapHeader.o \
		moc_ZIPHandler.o \
		moc_Supervisor.o \
		moc_quagzipfile.o \
		moc_quaziodevice.o \
		moc_quazipfile.o \
		moc_QtHttpServer.o \
		moc_QtHttpReply.o \
		moc_QtHttpRequest.o \
		moc_QtHttpClientWrapper.o
DIST          = quazip/QuaZipConfig.cmake.in \
		quazip/quazip.pc.cmakein \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		MAIN_MOBILE.pro CallbellHandler.h \
		CameraView.h \
		ExtProcess.h \
		GlobalHeader.h \
		IPCHandler.h \
		MapHandler.h \
		MapViewer.h \
		ServerHandler.h \
		python_wrapper.h \
		spline.h \
		Keyemitter.h \
		Logger.h \
		MapHeader.h \
		automata.h \
		ZIPHandler.h \
		cv_to_qt.h \
		Supervisor.h \
		quazip/JlCompress.h \
		quazip/ioapi.h \
		quazip/minizip_crypt.h \
		quazip/quaadler32.h \
		quazip/quachecksum32.h \
		quazip/quacrc32.h \
		quazip/quagzipfile.h \
		quazip/quaziodevice.h \
		quazip/quazip.h \
		quazip/quazip_global.h \
		quazip/quazip_qt_compat.h \
		quazip/quazipdir.h \
		quazip/quazipfile.h \
		quazip/quazipfileinfo.h \
		quazip/quazipnewinfo.h \
		quazip/unzip.h \
		quazip/zip.h \
		websocket/QtHttpServer.h \
		websocket/QtHttpReply.h \
		websocket/QtHttpRequest.h \
		websocket/QtHttpHeader.h \
		websocket/QtHttpClientWrapper.h CallbellHandler.cpp \
		CameraView.cpp \
		ExtProcess.cpp \
		IPCHandler.cpp \
		MapHandler.cpp \
		MapViewer.cpp \
		ServerHandler.cpp \
		ZIPHandler.cpp \
		automata.cpp \
		cv_to_qt.cpp \
		Logger.cpp \
		Supervisor.cpp \
		main.cpp \
		quazip/JlCompress.cpp \
		quazip/qioapi.cpp \
		quazip/quaadler32.cpp \
		quazip/quachecksum32.cpp \
		quazip/quacrc32.cpp \
		quazip/quagzipfile.cpp \
		quazip/quaziodevice.cpp \
		quazip/quazip.cpp \
		quazip/quazipdir.cpp \
		quazip/quazipfile.cpp \
		quazip/quazipfileinfo.cpp \
		quazip/quazipnewinfo.cpp \
		quazip/unzip.c \
		quazip/zip.c \
		websocket/QtHttpServer.cpp \
		websocket/QtHttpReply.cpp \
		websocket/QtHttpRequest.cpp \
		websocket/QtHttpHeader.cpp \
		websocket/QtHttpClientWrapper.cpp
QMAKE_TARGET  = MAIN_MOBILE
DESTDIR       = 
TARGET        = MAIN_MOBILE


first: all
####### Build rules

MAIN_MOBILE:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MAIN_MOBILE.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		MAIN_MOBILE.pro \
		qml_qmlcache.qrc
	$(QMAKE) -o Makefile MAIN_MOBILE.pro -spec linux-g++ CONFIG+=debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
MAIN_MOBILE.pro:
qml_qmlcache.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile MAIN_MOBILE.pro -spec linux-g++ CONFIG+=debug

qmake_all: FORCE


all: Makefile MAIN_MOBILE

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Popup_notice.qml Item_radioButton.qml Popup_patrol.qml Popup_password.qml Page_moving.qml Page_charge.qml Tool_Keyboard.qml Item_button.qml Item_menubar.qml Popup_help.qml Page_pickup.qml Page_MoveFail.qml Item_buttons.qml Item_statusbar.qml Page_setting.qml MAP_FULL2.qml main.qml Page_init.qml Item_localization.qml Item_progressCircle.qml Page_kitchen.qml Popup_patrol_page.qml Page_mapping.qml Page_menus.qml Tool_KeyPad.qml Page_pickup_calling.qml Popup_map_list.qml Item_ProgressBar.qml Popup_test_tts.qml Page_log.qml Page_map.qml Item_CircleP.qml Item_buttonRectIcon.qml Page_annotation.qml $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents qml_qmlcache.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CallbellHandler.h CameraView.h ExtProcess.h GlobalHeader.h IPCHandler.h MapHandler.h MapViewer.h ServerHandler.h python_wrapper.h spline.h Keyemitter.h Logger.h MapHeader.h automata.h ZIPHandler.h cv_to_qt.h Supervisor.h quazip/JlCompress.h quazip/ioapi.h quazip/minizip_crypt.h quazip/quaadler32.h quazip/quachecksum32.h quazip/quacrc32.h quazip/quagzipfile.h quazip/quaziodevice.h quazip/quazip.h quazip/quazip_global.h quazip/quazip_qt_compat.h quazip/quazipdir.h quazip/quazipfile.h quazip/quazipfileinfo.h quazip/quazipnewinfo.h quazip/unzip.h quazip/zip.h websocket/QtHttpServer.h websocket/QtHttpReply.h websocket/QtHttpRequest.h websocket/QtHttpHeader.h websocket/QtHttpClientWrapper.h $(DISTDIR)/
	$(COPY_FILE) --parents CallbellHandler.cpp CameraView.cpp ExtProcess.cpp IPCHandler.cpp MapHandler.cpp MapViewer.cpp ServerHandler.cpp ZIPHandler.cpp automata.cpp cv_to_qt.cpp Logger.cpp Supervisor.cpp main.cpp quazip/JlCompress.cpp quazip/qioapi.cpp quazip/quaadler32.cpp quazip/quachecksum32.cpp quazip/quacrc32.cpp quazip/quagzipfile.cpp quazip/quaziodevice.cpp quazip/quazip.cpp quazip/quazipdir.cpp quazip/quazipfile.cpp quazip/quazipfileinfo.cpp quazip/quazipnewinfo.cpp quazip/unzip.c quazip/zip.c websocket/QtHttpServer.cpp websocket/QtHttpReply.cpp websocket/QtHttpRequest.cpp websocket/QtHttpHeader.cpp websocket/QtHttpClientWrapper.cpp $(DISTDIR)/
	$(COPY_FILE) --parents lang_en.ts lang_eddn.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_qmlcache_make_all: Popup_notice_qml.cpp Item_radioButton_qml.cpp Popup_patrol_qml.cpp Popup_password_qml.cpp Page_moving_qml.cpp Page_charge_qml.cpp Tool_Keyboard_qml.cpp Item_button_qml.cpp Item_menubar_qml.cpp Popup_help_qml.cpp Page_pickup_qml.cpp Page_MoveFail_qml.cpp Item_buttons_qml.cpp Item_statusbar_qml.cpp Page_setting_qml.cpp MAP_FULL2_qml.cpp main_qml.cpp Page_init_qml.cpp Item_localization_qml.cpp Item_progressCircle_qml.cpp Page_kitchen_qml.cpp Popup_patrol_page_qml.cpp Page_mapping_qml.cpp Page_menus_qml.cpp Tool_KeyPad_qml.cpp Page_pickup_calling_qml.cpp Popup_map_list_qml.cpp Item_ProgressBar_qml.cpp Popup_test_tts_qml.cpp Page_log_qml.cpp Page_map_qml.cpp Item_CircleP_qml.cpp Item_buttonRectIcon_qml.cpp Page_annotation_qml.cpp
compiler_qmlcache_clean:
	-$(DEL_FILE) Popup_notice_qml.cpp Item_radioButton_qml.cpp Popup_patrol_qml.cpp Popup_password_qml.cpp Page_moving_qml.cpp Page_charge_qml.cpp Tool_Keyboard_qml.cpp Item_button_qml.cpp Item_menubar_qml.cpp Popup_help_qml.cpp Page_pickup_qml.cpp Page_MoveFail_qml.cpp Item_buttons_qml.cpp Item_statusbar_qml.cpp Page_setting_qml.cpp MAP_FULL2_qml.cpp main_qml.cpp Page_init_qml.cpp Item_localization_qml.cpp Item_progressCircle_qml.cpp Page_kitchen_qml.cpp Popup_patrol_page_qml.cpp Page_mapping_qml.cpp Page_menus_qml.cpp Tool_KeyPad_qml.cpp Page_pickup_calling_qml.cpp Popup_map_list_qml.cpp Item_ProgressBar_qml.cpp Popup_test_tts_qml.cpp Page_log_qml.cpp Page_map_qml.cpp Item_CircleP_qml.cpp Item_buttonRectIcon_qml.cpp Page_annotation_qml.cpp
Popup_notice_qml.cpp: Popup_notice.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Popup_notice_qml.cpp Popup_notice.qml

Item_radioButton_qml.cpp: Item_radioButton.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Item_radioButton_qml.cpp Item_radioButton.qml

Popup_patrol_qml.cpp: Popup_patrol.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Popup_patrol_qml.cpp Popup_patrol.qml

Popup_password_qml.cpp: Popup_password.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Popup_password_qml.cpp Popup_password.qml

Page_moving_qml.cpp: Page_moving.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_moving_qml.cpp Page_moving.qml

Page_charge_qml.cpp: Page_charge.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_charge_qml.cpp Page_charge.qml

Tool_Keyboard_qml.cpp: Tool_Keyboard.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Tool_Keyboard_qml.cpp Tool_Keyboard.qml

Item_button_qml.cpp: Item_button.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Item_button_qml.cpp Item_button.qml

Item_menubar_qml.cpp: Item_menubar.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Item_menubar_qml.cpp Item_menubar.qml

Popup_help_qml.cpp: Popup_help.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Popup_help_qml.cpp Popup_help.qml

Page_pickup_qml.cpp: Page_pickup.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_pickup_qml.cpp Page_pickup.qml

Page_MoveFail_qml.cpp: Page_MoveFail.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_MoveFail_qml.cpp Page_MoveFail.qml

Item_buttons_qml.cpp: Item_buttons.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Item_buttons_qml.cpp Item_buttons.qml

Item_statusbar_qml.cpp: Item_statusbar.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Item_statusbar_qml.cpp Item_statusbar.qml

Page_setting_qml.cpp: Page_setting.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_setting_qml.cpp Page_setting.qml

MAP_FULL2_qml.cpp: MAP_FULL2.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o MAP_FULL2_qml.cpp MAP_FULL2.qml

main_qml.cpp: main.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o main_qml.cpp main.qml

Page_init_qml.cpp: Page_init.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_init_qml.cpp Page_init.qml

Item_localization_qml.cpp: Item_localization.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Item_localization_qml.cpp Item_localization.qml

Item_progressCircle_qml.cpp: Item_progressCircle.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Item_progressCircle_qml.cpp Item_progressCircle.qml

Page_kitchen_qml.cpp: Page_kitchen.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_kitchen_qml.cpp Page_kitchen.qml

Popup_patrol_page_qml.cpp: Popup_patrol_page.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Popup_patrol_page_qml.cpp Popup_patrol_page.qml

Page_mapping_qml.cpp: Page_mapping.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_mapping_qml.cpp Page_mapping.qml

Page_menus_qml.cpp: Page_menus.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_menus_qml.cpp Page_menus.qml

Tool_KeyPad_qml.cpp: Tool_KeyPad.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Tool_KeyPad_qml.cpp Tool_KeyPad.qml

Page_pickup_calling_qml.cpp: Page_pickup_calling.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_pickup_calling_qml.cpp Page_pickup_calling.qml

Popup_map_list_qml.cpp: Popup_map_list.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Popup_map_list_qml.cpp Popup_map_list.qml

Item_ProgressBar_qml.cpp: Item_ProgressBar.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Item_ProgressBar_qml.cpp Item_ProgressBar.qml

Popup_test_tts_qml.cpp: Popup_test_tts.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Popup_test_tts_qml.cpp Popup_test_tts.qml

Page_log_qml.cpp: Page_log.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_log_qml.cpp Page_log.qml

Page_map_qml.cpp: Page_map.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_map_qml.cpp Page_map.qml

Item_CircleP_qml.cpp: Item_CircleP.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Item_CircleP_qml.cpp Item_CircleP.qml

Item_buttonRectIcon_qml.cpp: Item_buttonRectIcon.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Item_buttonRectIcon_qml.cpp Item_buttonRectIcon.qml

Page_annotation_qml.cpp: Page_annotation.qml \
		/usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource=/home/rainbow/UI_MOBILE_TEMP/qml.qrc -o Page_annotation_qml.cpp Page_annotation.qml

compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
qmlcache_loader.cpp: qml.qrc /usr/lib/qt5/bin/qmlcachegen
	/usr/lib/qt5/bin/qmlcachegen --resource-file-mapping=/home/rainbow/UI_MOBILE_TEMP/qml.qrc=/home/rainbow/UI_MOBILE_TEMP/qml_qmlcache.qrc -o qmlcache_loader.cpp qml.qrc

compiler_rcc_make_all: qrc_qml_qmlcache.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml_qmlcache.cpp
qrc_qml_qmlcache.cpp: qml_qmlcache.qrc \
		/usr/lib/qt5/bin/rcc \
		Popup_notice.qml \
		Item_radioButton.qml \
		Popup_patrol.qml \
		lang_eddn.qm \
		Popup_password.qml \
		Page_moving.qml \
		Page_charge.qml \
		Tool_Keyboard.qml \
		Item_button.qml \
		Item_menubar.qml \
		Popup_help.qml \
		Page_pickup.qml \
		Page_MoveFail.qml \
		Item_buttons.qml \
		Item_statusbar.qml \
		Page_setting.qml \
		MAP_FULL2.qml \
		main.qml \
		Page_init.qml \
		Item_localization.qml \
		Item_progressCircle.qml \
		Page_kitchen.qml \
		Popup_patrol_page.qml \
		Page_mapping.qml \
		Page_menus.qml \
		Tool_KeyPad.qml \
		Page_pickup_calling.qml \
		Popup_map_list.qml \
		Item_ProgressBar.qml \
		Popup_test_tts.qml \
		Page_log.qml \
		Page_map.qml \
		Item_CircleP.qml \
		Item_buttonRectIcon.qml \
		Page_annotation.qml \
		bgm/battery.mp3 \
		bgm/click.wav \
		bgm/serving.mp3 \
		bgm/song.mp3 \
		bgm/click3.wav \
		bgm/click3.mp3 \
		bgm/click_start.wav \
		bgm/click2.wav \
		bgm/click_error.wav \
		image/image_robot_temp.png \
		image/face_normal.gif \
		image/battery_1.png \
		image/robot_head_sleep.png \
		image/battery_2.png \
		image/face_cry2.gif \
		image/warning.png \
		image/battery_3.png \
		image/robot_clear.png \
		image/robot_pickup.png \
		image/icon_warning.png \
		image/loading.gif \
		image/joy_finger.png \
		image/face_surprise2.gif \
		image/face_normal2.gif \
		image/robot_moving.png \
		image/robot_callme.png \
		image/robot_move_wait.png \
		image/image_patrol.png \
		image/robot_head.png \
		image/image_location.png \
		image/battery_full.png \
		image/robot_move_charge.png \
		image/image_annot.png \
		image/image_lock.png \
		image/face_cry.gif \
		image/face_surprise.gif \
		image/image_localization.png \
		image/image_slam.png \
		image/loading_rb.gif \
		image/robot_manual.gif \
		image/rainbow3.png \
		image/joy_background.png \
		image/image_localization_reset.png \
		icon/icon_server_disconnect.png \
		icon/btn_reset2.png \
		icon/clock.png \
		icon/joy_left.png \
		icon/icon_meta_save.png \
		icon/icon_home_2.png \
		icon/icon_lock_2.png \
		icon/icon-drawing-square.png \
		icon/bat_1.png \
		icon/motor_power_off.png \
		icon/btn_no.png \
		icon/save_r.png \
		icon/icon_reset.png \
		icon/joystick_back.png \
		icon/record_r.png \
		icon/icon_init.png \
		icon/data_green.png \
		icon/load_r.png \
		icon/bat_charge.png \
		icon/keyboard_down.png \
		icon/btn_home.png \
		icon/stop_r.png \
		icon/icon_local_error.png \
		icon/btn_minimize.png \
		icon/icon_home_1.png \
		icon/icon_obs.png \
		icon/icon_warning_1.png \
		icon/motor_power_on.png \
		icon/icon_joy_disconnect.png \
		icon/bat_large_full.png \
		icon/icon_undo.png \
		icon/image_emergency.png \
		icon/icon_location.png \
		icon/joy_right.png \
		icon/keyboard_up.png \
		icon/icon-drawing-free\ drawing.png \
		icon/btn_wait.png \
		icon/image_setting.png \
		icon/icon_slowarea.png \
		icon/icon_edit.png \
		icon/icon_manualmove.png \
		icon/icon_mapping_start.png \
		icon/btn_lock.png \
		icon/icon_remove.png \
		icon/icon_transmit_server.png \
		icon/icon_point_1.png \
		icon/icon_annot_save.png \
		icon/btn_map.png \
		icon/icon_joy_connect.png \
		icon/icon_erase.png \
		icon/icon_set_init.png \
		icon/btn_setting.png \
		icon/data_gray.png \
		icon/icon_move.png \
		icon/icon_charge_2.png \
		icon/image_map.png \
		icon/icon_non_mute.png \
		icon/btn_confirm.png \
		icon/icon_test_play.png \
		icon/image_emergency_push.png \
		icon/bat_large_3.png \
		icon/keyboard_left.png \
		icon/icon_avoid.png \
		icon/icon_point.png \
		icon/btn_reset.png \
		icon/bat_large_charge.png \
		icon/icon_redo.png \
		icon/btn_yes.png \
		icon/icon_random_b.png \
		icon/icon_lcm_discon.png \
		icon/bat_3.png \
		icon/icon_warning.png \
		icon/joystick_thumb.png \
		icon/icon_server_download.png \
		icon/btn_menu.png \
		icon/icon_bookmark.png \
		icon/icon_auto_init.png \
		icon/icon_charge_1.png \
		icon/icon_motor_error.png \
		icon/icon_motor_hot.png \
		icon/joy_down.png \
		icon/icon_cancelpath.png \
		icon/icon_power.png \
		icon/icon_server_connect.png \
		icon/icon_error.png \
		icon/icon_random.png \
		icon/play_r.png \
		icon/icon_mapping.png \
		icon/bat_large_2.png \
		icon/icon_obj_no.png \
		icon/cursor.png \
		icon/icon-wall.png \
		icon/icon_connect_error.png \
		icon/icon_cur.png \
		icon/icon_stop.png \
		icon/icon_local_auto.png \
		icon/icon_local_manual.png \
		icon/icon_lidar.png \
		icon/icon_mute.png \
		icon/icon_test_stop.png \
		icon/icon_draw.png \
		icon/bat_2.png \
		icon/icon_open.png \
		icon/icon_wall.png \
		icon/joy_up.png \
		icon/btn_charge.png \
		icon/keyboard_right.png \
		icon/icon_run.png \
		icon/icon_repeat_b.png \
		icon/icon-drawing-curve.png \
		icon/icon_add.png \
		icon/patrol_down.png \
		icon/icon_emergency.png \
		icon/icon_trashcan.png \
		icon/icon_researching.png \
		icon/bat_large_1.png \
		icon/icon_obj_yes.png \
		icon/bat_full.png \
		icon/icon-drawing-polygon.png \
		voice/child_stop_mapping.mp3 \
		voice/woman_start_charging.mp3 \
		voice/woman_sorry.mp3 \
		voice/child_start_operation.mp3 \
		voice/woman_stop_charging.mp3 \
		voice/woman_pickup_1.mp3 \
		voice/child_start_move_resting.mp3 \
		voice/child_start_next_moving.mp3 \
		voice/woman_start_move_resting.mp3 \
		voice/child_funny_working_hard.mp3 \
		voice/woman_start_next_moving.mp3 \
		voice/woman_start_patrol.mp3 \
		voice/child_stop_charging.mp3 \
		voice/woman_serving.mp3 \
		voice/woman_charging.mp3 \
		voice/child_pickup_1.mp3 \
		voice/woman_hello_rb.mp3 \
		voice/woman_stop_mapping.mp3 \
		voice/child_serving.mp3 \
		voice/woman_funny_working_hard.mp3 \
		voice/child_charging.mp3 \
		voice/child_wait.mp3 \
		voice/child_hello_rb.mp3 \
		voice/child_sorry.mp3 \
		voice/child_wait_go_away.mp3 \
		voice/child_rb_fighting.mp3 \
		voice/woman_rb_fighting.mp3 \
		voice/woman_thank.mp3 \
		voice/woman_start_mapping.mp3 \
		voice/woman_error_no_path.mp3 \
		voice/woman_error_emo.mp3 \
		voice/woman_error.mp3 \
		voice/child_resume_path.mp3 \
		voice/woman_resume_path.mp3 \
		voice/child_thank_enjoy.mp3 \
		voice/woman_hello.mp3 \
		voice/woman_thank_enjoy.mp3 \
		voice/child_path_finding.mp3 \
		voice/woman_wait_go_away.mp3 \
		voice/child_low_battery.mp3 \
		voice/child_error_emo.mp3 \
		voice/child_start_mapping.mp3 \
		voice/child_error_no_path.mp3 \
		voice/woman_low_battery.mp3 \
		voice/child_thank.mp3 \
		voice/child_hello.mp3 \
		voice/woman_wait_path.mp3 \
		voice/woman_start_operation.mp3 \
		voice/child_error.mp3 \
		voice/child_pickup_confirm.mp3 \
		voice/woman_pickup_3.mp3 \
		voice/woman_pickup_confirm.mp3 \
		voice/child_error_localization.mp3 \
		voice/woman_start_serving.mp3 \
		voice/child_error_call_manager.mp3 \
		voice/child_pickup_3.mp3 \
		voice/child_start_move_charge.mp3 \
		voice/woman_start_move_charge.mp3 \
		voice/child_error_move_count.mp3 \
		voice/woman_pickup_drinks.mp3 \
		voice/woman_error_localization.mp3 \
		voice/woman_error_call_manager.mp3 \
		voice/child_wait_robot_location.mp3 \
		voice/woman_path_finding.mp3 \
		voice/child_cancel_path.mp3 \
		voice/woman_wait.mp3 \
		voice/woman_cancel_path.mp3 \
		voice/child_pickup_drinks.mp3 \
		voice/woman_start_calling.mp3 \
		voice/child_wait_path.mp3 \
		voice/woman_pickup_2.mp3 \
		voice/child_pickup_calling.mp3 \
		voice/child_start_serving.mp3 \
		voice/woman_pickup_calling.mp3 \
		voice/woman_error_move_count.mp3 \
		voice/child_start_patrol.mp3 \
		voice/child_motor_lock_off.mp3 \
		voice/child_wait_other_robot.mp3 \
		voice/child_start_calling.mp3 \
		voice/woman_motor_lock_off.mp3 \
		voice/child_pickup_2.mp3 \
		voice/woman_wait_other_robot.mp3 \
		voice/child_start_charging.mp3 \
		voice/woman_wait_robot_location.mp3 \
		font/NotoSansKR-Medium.otf \
		font/NotoSansKR-Light.otf
	/usr/lib/qt5/bin/rcc -name qml_qmlcache qml_qmlcache.qrc -o qrc_qml_qmlcache.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	ccache g++ -pipe -g -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_CallbellHandler.cpp moc_CameraView.cpp moc_ExtProcess.cpp moc_IPCHandler.cpp moc_MapHandler.cpp moc_MapViewer.cpp moc_ServerHandler.cpp moc_Keyemitter.cpp moc_Logger.cpp moc_MapHeader.cpp moc_ZIPHandler.cpp moc_Supervisor.cpp moc_quagzipfile.cpp moc_quaziodevice.cpp moc_quazipfile.cpp moc_QtHttpServer.cpp moc_QtHttpReply.cpp moc_QtHttpRequest.cpp moc_QtHttpClientWrapper.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_CallbellHandler.cpp moc_CameraView.cpp moc_ExtProcess.cpp moc_IPCHandler.cpp moc_MapHandler.cpp moc_MapViewer.cpp moc_ServerHandler.cpp moc_Keyemitter.cpp moc_Logger.cpp moc_MapHeader.cpp moc_ZIPHandler.cpp moc_Supervisor.cpp moc_quagzipfile.cpp moc_quaziodevice.cpp moc_quazipfile.cpp moc_QtHttpServer.cpp moc_QtHttpReply.cpp moc_QtHttpRequest.cpp moc_QtHttpClientWrapper.cpp
moc_CallbellHandler.cpp: CallbellHandler.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CallbellHandler.h -o moc_CallbellHandler.cpp

moc_CameraView.cpp: CameraView.h \
		MapHeader.h \
		cv_to_qt.h \
		GlobalHeader.h \
		Logger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CameraView.h -o moc_CameraView.cpp

moc_ExtProcess.cpp: ExtProcess.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ExtProcess.h -o moc_ExtProcess.cpp

moc_IPCHandler.cpp: IPCHandler.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include IPCHandler.h -o moc_IPCHandler.cpp

moc_MapHandler.cpp: MapHandler.h \
		spline.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapHandler.h -o moc_MapHandler.cpp

moc_MapViewer.cpp: MapViewer.h \
		MapHeader.h \
		cv_to_qt.h \
		spline.h \
		GlobalHeader.h \
		Logger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapViewer.h -o moc_MapViewer.cpp

moc_ServerHandler.cpp: ServerHandler.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h \
		ZIPHandler.h \
		quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/JlCompress.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		websocket/QtHttpServer.h \
		websocket/QtHttpRequest.h \
		websocket/QtHttpReply.h \
		websocket/QtHttpHeader.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ServerHandler.h -o moc_ServerHandler.cpp

moc_Keyemitter.cpp: Keyemitter.h \
		automata.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Keyemitter.h -o moc_Keyemitter.cpp

moc_Logger.cpp: Logger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Logger.h -o moc_Logger.cpp

moc_MapHeader.cpp: MapHeader.h \
		cv_to_qt.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapHeader.h -o moc_MapHeader.cpp

moc_ZIPHandler.cpp: ZIPHandler.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h \
		quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/JlCompress.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ZIPHandler.h -o moc_ZIPHandler.cpp

moc_Supervisor.cpp: Supervisor.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h \
		CallbellHandler.h \
		ZIPHandler.h \
		quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/JlCompress.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		python_wrapper.h \
		IPCHandler.h \
		ServerHandler.h \
		websocket/QtHttpServer.h \
		websocket/QtHttpRequest.h \
		websocket/QtHttpReply.h \
		websocket/QtHttpHeader.h \
		MapView.h \
		spline.h \
		MapHandler.h \
		ExtProcess.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Supervisor.h -o moc_Supervisor.cpp

moc_quagzipfile.cpp: quazip/quagzipfile.h \
		quazip/quazip_global.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include quazip/quagzipfile.h -o moc_quagzipfile.cpp

moc_quaziodevice.cpp: quazip/quaziodevice.h \
		quazip/quazip_global.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include quazip/quaziodevice.h -o moc_quaziodevice.cpp

moc_quazipfile.cpp: quazip/quazipfile.h \
		quazip/quazip_global.h \
		quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazipfileinfo.h \
		quazip/quazipnewinfo.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include quazip/quazipfile.h -o moc_quazipfile.cpp

moc_QtHttpServer.cpp: websocket/QtHttpServer.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include websocket/QtHttpServer.h -o moc_QtHttpServer.cpp

moc_QtHttpReply.cpp: websocket/QtHttpReply.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include websocket/QtHttpReply.h -o moc_QtHttpReply.cpp

moc_QtHttpRequest.cpp: websocket/QtHttpRequest.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include websocket/QtHttpRequest.h -o moc_QtHttpRequest.cpp

moc_QtHttpClientWrapper.cpp: websocket/QtHttpClientWrapper.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/UI_MOBILE_TEMP/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/UI_MOBILE_TEMP -I/usr/include/python3.10 -I/usr/include/opencv4 -I/usr/local/include -I/usr/local/include/QuaZip-Qt5-1.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.3/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.3/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include websocket/QtHttpClientWrapper.h -o moc_QtHttpClientWrapper.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_qmlcache_clean compiler_qmlcache_loader_clean compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

CallbellHandler.o: CallbellHandler.cpp CallbellHandler.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CallbellHandler.o CallbellHandler.cpp

CameraView.o: CameraView.cpp CameraView.h \
		MapHeader.h \
		cv_to_qt.h \
		GlobalHeader.h \
		Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CameraView.o CameraView.cpp

ExtProcess.o: ExtProcess.cpp ExtProcess.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExtProcess.o ExtProcess.cpp

IPCHandler.o: IPCHandler.cpp IPCHandler.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IPCHandler.o IPCHandler.cpp

MapHandler.o: MapHandler.cpp MapHandler.h \
		spline.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MapHandler.o MapHandler.cpp

MapViewer.o: MapViewer.cpp MapViewer.h \
		MapHeader.h \
		cv_to_qt.h \
		spline.h \
		GlobalHeader.h \
		Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MapViewer.o MapViewer.cpp

ServerHandler.o: ServerHandler.cpp ServerHandler.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h \
		ZIPHandler.h \
		quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/JlCompress.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		websocket/QtHttpServer.h \
		websocket/QtHttpRequest.h \
		websocket/QtHttpReply.h \
		websocket/QtHttpHeader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ServerHandler.o ServerHandler.cpp

ZIPHandler.o: ZIPHandler.cpp ZIPHandler.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h \
		quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/JlCompress.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ZIPHandler.o ZIPHandler.cpp

automata.o: automata.cpp automata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o automata.o automata.cpp

cv_to_qt.o: cv_to_qt.cpp cv_to_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cv_to_qt.o cv_to_qt.cpp

Logger.o: Logger.cpp Logger.h \
		GlobalHeader.h \
		MapHeader.h \
		cv_to_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Logger.o Logger.cpp

Supervisor.o: Supervisor.cpp Supervisor.h \
		GlobalHeader.h \
		Logger.h \
		MapHeader.h \
		cv_to_qt.h \
		CallbellHandler.h \
		ZIPHandler.h \
		quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/JlCompress.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		python_wrapper.h \
		IPCHandler.h \
		ServerHandler.h \
		websocket/QtHttpServer.h \
		websocket/QtHttpRequest.h \
		websocket/QtHttpReply.h \
		websocket/QtHttpHeader.h \
		MapView.h \
		spline.h \
		MapHandler.h \
		ExtProcess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Supervisor.o Supervisor.cpp

main.o: main.cpp CameraView.h \
		MapHeader.h \
		cv_to_qt.h \
		GlobalHeader.h \
		Logger.h \
		Supervisor.h \
		CallbellHandler.h \
		ZIPHandler.h \
		quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/JlCompress.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		python_wrapper.h \
		IPCHandler.h \
		ServerHandler.h \
		websocket/QtHttpServer.h \
		websocket/QtHttpRequest.h \
		websocket/QtHttpReply.h \
		websocket/QtHttpHeader.h \
		MapView.h \
		spline.h \
		MapHandler.h \
		ExtProcess.h \
		MapViewer.h \
		Keyemitter.h \
		automata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

JlCompress.o: quazip/JlCompress.cpp quazip/JlCompress.h \
		quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JlCompress.o quazip/JlCompress.cpp

qioapi.o: quazip/qioapi.cpp quazip/ioapi.h \
		quazip/quazip_global.h \
		quazip/quazip_qt_compat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qioapi.o quazip/qioapi.cpp

quaadler32.o: quazip/quaadler32.cpp quazip/quaadler32.h \
		quazip/quachecksum32.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quaadler32.o quazip/quaadler32.cpp

quachecksum32.o: quazip/quachecksum32.cpp quazip/quachecksum32.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quachecksum32.o quazip/quachecksum32.cpp

quacrc32.o: quazip/quacrc32.cpp quazip/quacrc32.h \
		quazip/quachecksum32.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quacrc32.o quazip/quacrc32.cpp

quagzipfile.o: quazip/quagzipfile.cpp quazip/quagzipfile.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quagzipfile.o quazip/quagzipfile.cpp

quaziodevice.o: quazip/quaziodevice.cpp quazip/quaziodevice.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quaziodevice.o quazip/quaziodevice.cpp

quazip.o: quazip/quazip.cpp quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazip.o quazip/quazip.cpp

quazipdir.o: quazip/quazipdir.cpp quazip/quazipdir.h \
		quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipdir.o quazip/quazipdir.cpp

quazipfile.o: quazip/quazipfile.cpp quazip/quazipfile.h \
		quazip/quazip_global.h \
		quazip/quazip.h \
		quazip/quazip_qt_compat.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazipfileinfo.h \
		quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipfile.o quazip/quazipfile.cpp

quazipfileinfo.o: quazip/quazipfileinfo.cpp quazip/quazipfileinfo.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipfileinfo.o quazip/quazipfileinfo.cpp

quazipnewinfo.o: quazip/quazipnewinfo.cpp quazip/quazipnewinfo.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazip_qt_compat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipnewinfo.o quazip/quazipnewinfo.cpp

unzip.o: quazip/unzip.c quazip/unzip.h \
		quazip/ioapi.h \
		quazip/minizip_crypt.h \
		quazip/quazip_global.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o unzip.o quazip/unzip.c

zip.o: quazip/zip.c quazip/zip.h \
		quazip/ioapi.h \
		quazip/minizip_crypt.h \
		quazip/quazip_global.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o zip.o quazip/zip.c

QtHttpServer.o: websocket/QtHttpServer.cpp websocket/QtHttpServer.h \
		websocket/QtHttpRequest.h \
		websocket/QtHttpReply.h \
		websocket/QtHttpClientWrapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtHttpServer.o websocket/QtHttpServer.cpp

QtHttpReply.o: websocket/QtHttpReply.cpp websocket/QtHttpReply.h \
		websocket/QtHttpHeader.h \
		websocket/QtHttpServer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtHttpReply.o websocket/QtHttpReply.cpp

QtHttpRequest.o: websocket/QtHttpRequest.cpp websocket/QtHttpRequest.h \
		websocket/QtHttpHeader.h \
		websocket/QtHttpServer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtHttpRequest.o websocket/QtHttpRequest.cpp

QtHttpHeader.o: websocket/QtHttpHeader.cpp websocket/QtHttpHeader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtHttpHeader.o websocket/QtHttpHeader.cpp

QtHttpClientWrapper.o: websocket/QtHttpClientWrapper.cpp websocket/QtHttpClientWrapper.h \
		websocket/QtHttpRequest.h \
		websocket/QtHttpReply.h \
		websocket/QtHttpServer.h \
		websocket/QtHttpHeader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtHttpClientWrapper.o websocket/QtHttpClientWrapper.cpp

Popup_notice_qml.o: Popup_notice_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Popup_notice_qml.o Popup_notice_qml.cpp

Item_radioButton_qml.o: Item_radioButton_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item_radioButton_qml.o Item_radioButton_qml.cpp

Popup_patrol_qml.o: Popup_patrol_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Popup_patrol_qml.o Popup_patrol_qml.cpp

Popup_password_qml.o: Popup_password_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Popup_password_qml.o Popup_password_qml.cpp

Page_moving_qml.o: Page_moving_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_moving_qml.o Page_moving_qml.cpp

Page_charge_qml.o: Page_charge_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_charge_qml.o Page_charge_qml.cpp

Tool_Keyboard_qml.o: Tool_Keyboard_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tool_Keyboard_qml.o Tool_Keyboard_qml.cpp

Item_button_qml.o: Item_button_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item_button_qml.o Item_button_qml.cpp

Item_menubar_qml.o: Item_menubar_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item_menubar_qml.o Item_menubar_qml.cpp

Popup_help_qml.o: Popup_help_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Popup_help_qml.o Popup_help_qml.cpp

Page_pickup_qml.o: Page_pickup_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_pickup_qml.o Page_pickup_qml.cpp

Page_MoveFail_qml.o: Page_MoveFail_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_MoveFail_qml.o Page_MoveFail_qml.cpp

Item_buttons_qml.o: Item_buttons_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item_buttons_qml.o Item_buttons_qml.cpp

Item_statusbar_qml.o: Item_statusbar_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item_statusbar_qml.o Item_statusbar_qml.cpp

Page_setting_qml.o: Page_setting_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_setting_qml.o Page_setting_qml.cpp

MAP_FULL2_qml.o: MAP_FULL2_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MAP_FULL2_qml.o MAP_FULL2_qml.cpp

main_qml.o: main_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_qml.o main_qml.cpp

Page_init_qml.o: Page_init_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_init_qml.o Page_init_qml.cpp

Item_localization_qml.o: Item_localization_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item_localization_qml.o Item_localization_qml.cpp

Item_progressCircle_qml.o: Item_progressCircle_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item_progressCircle_qml.o Item_progressCircle_qml.cpp

Page_kitchen_qml.o: Page_kitchen_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_kitchen_qml.o Page_kitchen_qml.cpp

Popup_patrol_page_qml.o: Popup_patrol_page_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Popup_patrol_page_qml.o Popup_patrol_page_qml.cpp

Page_mapping_qml.o: Page_mapping_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_mapping_qml.o Page_mapping_qml.cpp

Page_menus_qml.o: Page_menus_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_menus_qml.o Page_menus_qml.cpp

Tool_KeyPad_qml.o: Tool_KeyPad_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tool_KeyPad_qml.o Tool_KeyPad_qml.cpp

Page_pickup_calling_qml.o: Page_pickup_calling_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_pickup_calling_qml.o Page_pickup_calling_qml.cpp

Popup_map_list_qml.o: Popup_map_list_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Popup_map_list_qml.o Popup_map_list_qml.cpp

Item_ProgressBar_qml.o: Item_ProgressBar_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item_ProgressBar_qml.o Item_ProgressBar_qml.cpp

Popup_test_tts_qml.o: Popup_test_tts_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Popup_test_tts_qml.o Popup_test_tts_qml.cpp

Page_log_qml.o: Page_log_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_log_qml.o Page_log_qml.cpp

Page_map_qml.o: Page_map_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_map_qml.o Page_map_qml.cpp

Item_CircleP_qml.o: Item_CircleP_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item_CircleP_qml.o Item_CircleP_qml.cpp

Item_buttonRectIcon_qml.o: Item_buttonRectIcon_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item_buttonRectIcon_qml.o Item_buttonRectIcon_qml.cpp

Page_annotation_qml.o: Page_annotation_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Page_annotation_qml.o Page_annotation_qml.cpp

qmlcache_loader.o: qmlcache_loader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlcache_loader.o qmlcache_loader.cpp

qrc_qml_qmlcache.o: qrc_qml_qmlcache.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml_qmlcache.o qrc_qml_qmlcache.cpp

moc_CallbellHandler.o: moc_CallbellHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CallbellHandler.o moc_CallbellHandler.cpp

moc_CameraView.o: moc_CameraView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CameraView.o moc_CameraView.cpp

moc_ExtProcess.o: moc_ExtProcess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ExtProcess.o moc_ExtProcess.cpp

moc_IPCHandler.o: moc_IPCHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_IPCHandler.o moc_IPCHandler.cpp

moc_MapHandler.o: moc_MapHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MapHandler.o moc_MapHandler.cpp

moc_MapViewer.o: moc_MapViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MapViewer.o moc_MapViewer.cpp

moc_ServerHandler.o: moc_ServerHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ServerHandler.o moc_ServerHandler.cpp

moc_Keyemitter.o: moc_Keyemitter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Keyemitter.o moc_Keyemitter.cpp

moc_Logger.o: moc_Logger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Logger.o moc_Logger.cpp

moc_MapHeader.o: moc_MapHeader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MapHeader.o moc_MapHeader.cpp

moc_ZIPHandler.o: moc_ZIPHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ZIPHandler.o moc_ZIPHandler.cpp

moc_Supervisor.o: moc_Supervisor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Supervisor.o moc_Supervisor.cpp

moc_quagzipfile.o: moc_quagzipfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quagzipfile.o moc_quagzipfile.cpp

moc_quaziodevice.o: moc_quaziodevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quaziodevice.o moc_quaziodevice.cpp

moc_quazipfile.o: moc_quazipfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quazipfile.o moc_quazipfile.cpp

moc_QtHttpServer.o: moc_QtHttpServer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtHttpServer.o moc_QtHttpServer.cpp

moc_QtHttpReply.o: moc_QtHttpReply.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtHttpReply.o moc_QtHttpReply.cpp

moc_QtHttpRequest.o: moc_QtHttpRequest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtHttpRequest.o moc_QtHttpRequest.cpp

moc_QtHttpClientWrapper.o: moc_QtHttpClientWrapper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtHttpClientWrapper.o moc_QtHttpClientWrapper.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/MAIN_MOBILE/bin || mkdir -p $(INSTALL_ROOT)/opt/MAIN_MOBILE/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/MAIN_MOBILE/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/MAIN_MOBILE/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/MAIN_MOBILE/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

